Ansible 1
Otus-DevOps-2018-09/darthnitrox_infra pull request #7
Opened 2019-01-30 11:28 UTC by darthnitrox

# Выполнено ДЗ №

 - [X] Основное ДЗ
 - [X] Задание со *

## В процессе сделано:
 Создан статический инвентори файл ini формат и yaml формат 
 Создан плейбук для деплоя приложения
Создан Динамический инвентори файл

## Как запустить проект:
 ansible all -m ping

## Как проверить работоспособность:
 Статус в консоли при выполнение
YOURE SERVER | SUCCESS => {
    "changed": false,
    "ping": "pong"
}

## PR checklist
 - [X] Выставил label с номером домашнего задания
 - [X] Выставил label с темой домашнего задания

2019-01-30 18:48 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Нужно внести некоторые изменения=)

2019-01-30 18:48 UTC, mrgreyves commented on ansible/clone.yml
> +  tasks:
Пропустили --- и лишний пробел поставили

2019-01-30 19:13 UTC, darthnitrox commented on ansible/clone.yml
> +  tasks:
Поправил.

2019-01-31 06:01 UTC, mrgreyves approved these changes
Апрув. Только не забудьте подправить clone.yml=)

2019-01-31 06:01 UTC, mrgreyves commented on ansible/clone.yml
> +  tasks:
![screenshot_5](https://user-images.githubusercontent.com/34331259/52006467-3e1d7100-24dd-11e9-8bad-b74299ec3ef3.jpg)
Вот тут еще лишний пробел, весь таск поехал. Советую использовать Visual studio code, он прекрасно работает с yaml=)

2019-02-22 08:42 UTC, merged